In this part of the assignment you have to implement multivariate gradient descent to find the minimas (local and global) of the given function:
Note : you can find different minimas by changing your initialisation.  
$f(x) = x^4 + x^2y^2 - y^2 + y^4 + 6$

In [8]:
import numpy as np

In [9]:
def call_func(func):
    def wrapper():
        func()
    return wrapper

In [62]:
def derivative(f, positions):
    return np.array([4*positions[0]**3 + 2*positions[0]*positions[1]**2, 4*positions[1]**3 -2*positions[1] + 2*positions[1]*positions[0]**2])

In [65]:
def multivariable_gradient_descent(func, positions, alpha = 0.1):
    epsilon = 1e-5
    weights = np.ones(len(positions))
    s = abs(sum(weights))
    count = 0
    new_positions = positions.copy()
    while s > epsilon:
        positions = new_positions.copy()
        count += 1
        weights = derivative(func, positions)
        s = abs(sum(weights))
        new_positions -= weights/max(100, s)
        while s > epsilon and all(new_positions == positions):
            new_positions -= weights/100
    return positions, count

In [66]:
positions = [1,1]
func = 5
multivariable_gradient_descent(func, positions)

(array([9.94526076e-06, 7.07106781e-01]), 1071)

In [67]:
positions = np.array([-2,-2], dtype='float64')
func = 5
multivariable_gradient_descent(func, positions)

(array([-9.97043752e-06, -7.07106781e-01]), 1073)

In [57]:
positions = np.array([50,50], dtype='float64')
func = 5
positions, count = multivariable_gradient_descent(func, positions)

array([99.99999756, 99.99999756])

849